# This file configures CodeCov to require 70% code coverage. New PRs can
# increase or decrease coverage--only the total coverage threshold matters.
coverage:
  status:
    project:
      default:
        target: 55% # we can improve this as we fix external issues
    patch: off # we can enable this if we figure out a reasonable policy

