site_name: "DTS: A Data Transfer System"

nav:
  - 'Home': 'index.md'
  - 'Administrator Guide':
    - 'Overview': 'admin/index.md'
    - 'Installing the DTS Locally': 'admin/installation.md'
    - 'Deploying the DTS via Docker': 'admin/deployment.md'
    - 'Configuring the DTS': 'admin/config.md'
    - 'Granting the DTS Access to a Globus Endpoint': 'admin/globus.md'
  - 'Integration Guide':
    - 'Overview': 'integration/index.md'
    - 'Provide Unique IDs and Metadata for Your Files': 'integration/resources.md'
    - 'Make Your Files Searchable': 'integration/search.md'
    - 'Provide a Staging Area for Your Files': 'integration/staging_area.md'
    - 'Stage Your Files on Request': 'integration/stage_files.md'
    - 'Provide a Way to Monitor File Staging': 'integration/staging_status.md'
    - 'Map ORCIDs to Local User Accounts': 'integration/local_user.md'
    - 'Glossary': 'integration/glossary.md'
  - 'Developer Guide':
    - 'Overview': 'developer/index.md'
    - 'Architecture Decision Records':
      - 'developer/adrs/index.md'
      - 'Transmitting Metadata': 'developer/adrs/transmit-metadata.md'
    - 'Code Organization':
      - 'auth package': 'developer/auth.md'
      - 'config package': 'developer/config.md'
      - 'credit package': 'developer/credit.md'
      - 'databases package': 'developer/databases.md'
      - 'endpoints package': 'developer/endpoints.md'
      - 'frictionless package': 'developer/frictionless.md'
      - 'services package': 'developer/services.md'
      - 'tasks package': 'developer/tasks.md'
    - 'Special Topics':
      - 'KBase Narrative import process': 'developer/kbase_import.md'

edit_uri: ""

theme:
  name: material
  palette:
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: cyan
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  features:
    - navigation.indices
    - navigation.instant
    - navigation.sections
    - navigation.top
#    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - tables

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6

repo_url: https://github.com/kbase/dts

use_directory_urls: false
