FROM --platform=linux/amd64 docker.io/coherellc/irods_client_s3_api:v0.5.0

ENV DEBIAN_FRONTEND=noninteractive

EXPOSE 9010

COPY s3-proxy-config.json /config.json
COPY plugin-config /plugin-config

ENTRYPOINT [ "irods_s3_api", "/config.json" ]